[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "multilogue"
version = "0.0.13"
authors = [
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"},
]
description = "Multilogue is a cooperative game of reasoning entities against ignorance, confusion and misunderstanding."
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
keywords = ["multilogue", "multilectic", "conversation", "ai"]
dependencies = [
    "requests >= 2.30.0",
    "PyGithub >= 1.59.0",
    "urllib3 >= 2.0.4",
    "openai >= 0.27.8",
    "tiktoken >= 0.4.0"
]
[project.urls]
"Homepage" = "https://github.com/multilogue/multilogue"
"Bug Tracker" = "https://github.com/multilogue/multilogue/issues"